/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "star’s blog",
  "description": "了解真相,你才能获得更多的自由",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Vue props传值监听",
      "frontmatter": {
        "navbar": true,
        "title": "Vue props传值监听"
      },
      "regularPath": "/Vue-01.html",
      "relativePath": "Vue-01.md",
      "key": "v-0b99e390",
      "path": "/Vue-01.html",
      "headers": [
        {
          "level": 3,
          "title": "vue父组件给子组件传递的参数发生改变时,子组件不能及时更新的问题",
          "slug": "vue父组件给子组件传递的参数发生改变时-子组件不能及时更新的问题"
        }
      ]
    },
    {
      "title": "关于我",
      "frontmatter": {
        "navbar": true
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-66959f94",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 3,
          "title": "5.24继续开始搭建博客",
          "slug": "_5-24继续开始搭建博客"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Star",
        "tagline": "在昏暗的森林，寻找那颗指引我前进的星辰",
        "actionText": "探索 →",
        "actionLink": "/vue-01.html",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-017826c7",
      "path": "/"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Vue",
        "items": [
          {
            "text": "Vue技术文档",
            "items": [
              {
                "text": "props传值更新",
                "link": "/vue-01"
              }
            ]
          }
        ]
      },
      {
        "text": "关于",
        "items": [
          {
            "text": "关于我",
            "items": [
              {
                "text": "自学前端心路历程",
                "link": "/about"
              }
            ]
          }
        ]
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ]
  }
}